<?xml version="1.0"?>

<st-source>
<time-stamp>From VisualWorks® Personal Use Edition, 7.9.1 of October 18, 2012 on August 7, 2019 at 5:26:37 PM</time-stamp>


<methods>
<class-id>FooDisplayModel class</class-id> <category>examples</category>

<body package="Foo-Display" selector="example1">example1	"FooDisplayModel example1."	| aModel |	aModel := FooDisplayModel new.	aModel open.	^aModel</body>
</methods>

</st-source>
